services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@weather-io.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin@123456}
    volumes:
      - weather-exports:/app/exports

  consumer:
    build:
      context: ../apps/consumer
      dockerfile: Dockerfile
    container_name: consumer
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - api

  producer:
    build:
      context: ../apps/producer
      dockerfile: Dockerfile
    container_name: producer
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - weather-exports:/app/exports
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Port AMQP
      - "15672:15672"   # Port Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    container_name: frontend
    ports:
      - "5673:5673"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  weather-exports:
